### ISSUE TITLE
As a developer, I want to `required_ssl` as configurable for external DB.

### ISSUE THREAD

**Issue by edwardstudy** [SUSE/kubecf#257] opened 2019-12-12 09:36 UTC
**Is your feature request related to a problem? Please describe.**
I had an external db instance and wanted to use it for kubecf.

But my db consumers failed to connect db, like diego-api:

```
{"timestamp":"2019-12-12T04:05:19.755380425Z","level":"info","source":"bbs","message":"bbs.starting","data":{}}
{"timestamp":"2019-12-12T04:05:19.798488967Z","level":"fatal","source":"bbs","message":"bbs.sql-failed-to-connect","data":{"error":"pq: no pg_hba.conf entry for host \"172.30.21.188\", user \"diegoadmin\", database \"diego\", SSL off","trace":"goroutine 1 [running]:\ncode.cloudfoundry.org/lager.(*logger).Fatal(0xc000144360, 0xcd49a3, 0x15, 0xdc42c0, 0xc00012a240, 0x0, 0x0, 0x0)\n\t/var/vcap/source/bbs/src/code.cloudfoundry.org/lager/logger.go:138 +0xc6\nmain.main()\n\t/var/vcap/source/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:139 +0x4a74\n"}}
panic: pq: no pg_hba.conf entry for host "172.30.21.188", user "diegoadmin", database "diego", SSL off

goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc000144360, 0xcd49a3, 0x15, 0xdc42c0, 0xc00012a240, 0x0, 0x0, 0x0)
	/var/vcap/source/bbs/src/code.cloudfoundry.org/lager/logger.go:162 +0x58c
main.main()
	/var/vcap/source/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:139 +0x4a74
```

And if I added `require_ssl` and fixed it, because my db instance has this strict requirement.

**Describe the solution you'd like**
A feature flag to set these strict values for each db consumers.

**Describe alternatives you've considered**
This feature should work with the current external db process: https://github.com/SUSE/kubecf/blob/master/deploy/helm/kubecf/values.yaml#L145
So we need to update the external db ops from cf-deployment or add new ops based on it.

**Additional context**

**Comment by qu1queee** [comment] 2019-12-12 09:40
+1 on this

**Comment by f0rmiga** [comment] 2019-12-12 19:54
Duplicate of https://github.com/SUSE/kubecf/issues/191.

**Closed by f0rmiga** 2019-12-12 19:54 UTC
